#!/bin/bash
#SBATCH -c 8
#SBATCH --time=01:00:00
#SBATCH --mem=5G
#SBATCH --qos=normal
#SBATCH --nodelist=cn06

# USER PARAMS ===========================================
EXECUTABLE=gammcor
WORK_DIR=/home/adam.sokol/QCHEM/TESTS/IntCholesky_H2O
OUT_FILE=/home/adam.sokol/QCHEM/PROFILING/QAWA/outs/memory
# DELAY=3

# SCRIPT ================================================
cd $WORK_DIR
$EXECUTABLE &

cd -
python mem_monitor.py $EXECUTABLE $USER $OUT_FILE

# sleep $DELAY

# cd $QAWA_DIR
# python mem_reporter.py